config/routes.rb
Rails.application.routes.draw do

  devise_for :trainers, controllers: {
  sessions:      'trainers/sessions',
  passwords:     'trainers/passwords',
  registrations: 'trainers/registrations'
  }
  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
  }

resources :identifications, only: :index
resources :top, only: :index do
  collection do
  get 'search'
  get 'trainer_search'
end

end
resources :users, only: [:show, :edit, :update]
resources :trainers, only: [:show, :edit, :update]
resources :posts, only: :create
resources :answers, only: [:new,:create]
 post  'relationships/:id'      =>  'relationships#create'
 # :idでモデルの持つid情報を取得

root 'top#index'
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :trainer
  belongs_to :post
  has_many :categories
  has_one :category, as: :categoable
end

app/models/category.rb
class Category < ActiveRecord::Base
   has_many :users
   has_many :trainers
end

app/models/place.rb
class Place < ActiveRecord::Base
  has_many :users
  has_many :trainers
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :trainer
  has_many :answers
  has_many :categories
  has_one :category, as: :categoable

has_attached_file :avatar, styles: { medium: "500x500>", thumb: "100x100>"}
  validates_attachment_content_type :avatar, content_type: ["image/jpg","image/jpeg","image/png"]

validates_presence_of :post, :title
  # after_create :create_category
  # private
  # def create_category
  #   self.create_category = Category.create(category: group_id,)
  # end

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base

belongs_to :following
belongs_to :follower, polymorphic: true



# belongs_to :follower, class_name: "User"
# # フォロワーする側を定義
# belongs_to :followed, class_name: "User"
# # フォローされる側を定義
# belongs_to :trainer
end

app/models/trainer.rb
class Trainer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :posts
         has_many :answers
         belongs_to :place
         belongs_to :category
         has_many :relationships, dependent: :destroy
         has_many :relationships, as: :follower, dependent: :destroy


  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>"}
  validates_attachment_content_type :avatar, content_type: ["image/jpg","image/jpeg","image/png"]

def full_profile?
    avatar? && profile?
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable

         has_many :posts
         has_many :answers
         belongs_to :place
         belongs_to :category
         has_many :relationships, dependent: :destroy
         has_many :relationships, as: :follower, dependent: :destroy




# has_many :active_relationships, class_name: "Relationship",
# foreign_key:"follower_user_id",
# dependent: :destroy

# has_many :passive_relationships, class_name: "Relationship",
# foreign_key:"followed_user_id",
# dependent: :destroy
# has_many :following_users, through: :active_relationships,source: :followed
# # フォローしているユーザー設定
# has_many :follower_users, through: :passive_relationships,source: :follower
# # フォロワされているの設定


  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>"}
  validates_attachment_content_type :avatar, content_type: ["image/jpg","image/jpeg","image/png"]

def full_profile?
    avatar? && profile?
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

 def new
    @post = Post.find(params[:post_id])
    @answer = Answer.new
    @answer.post_id = @post.id
 end

 def create
    @answer = Answer.create(answer_params)
      redirect_to :root and return
 end


 private
     def answer_params
      if user_signed_in?
      params.require(:answer).permit(:answer, :post_id).merge(user_id: current_user.id)

      elsif trainer_signed_in?
      params.require(:answer).permit(:answer, :post_id).merge(trainer_id: current_trainer.id,)
     end
 end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
# before_action :authenticate_user!
   before_action :identification_page
   before_action :configure_permitted_parameters, if: :devise_controller?


   def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up).push(:name)
    end

def identification_page
  unless user_signed_in? || trainer_signed_in?
    redirect_to identifications_url
  end
end

def after_sign_out_path_for(resource)
  '/users/sign_in'
end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

# def index
#     @posts = Post.all
#     @post = Post.new
# end

def create
  Post.create(post_params)
  redirect_to :root and return
end




private

def post_params
  if user_signed_in?
  params.require(:post).permit(:post, :title, :avatar, :place).merge(user_id: current_user.id)

elsif trainer_signed_in?
   params.require(:post).permit(:post, :title, :avatar, :place).merge(trainer_id: current_trainer.id)
end
end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

def create
  # binding.pry
  if user_signed_in?
    @user = current_user
    @user.relationships.create(following_id: params[:id], following_type: params[:type])
    elsif trainer_signed_in?
    @trainer = current_trainer
    @trainer.relationships.create(following_id: params[:id], following_type:params[:type])
    end
    redirect_to :root and return
end

 # private
 #    def following_params
       
 #      params.require(:relationship).permit().merge(follower_id: current_user.id,following_id: params[:id])
 #      elsif trainer_signed_in?
 #        params.require(:relationship).permit().merge(follower_id: current_trainer.id,following_id: params[:id])
 #      end
 #    end

end

app/controllers/top_controller.rb
class TopController < ApplicationController

    def index
        @users = User.all
        @post = Post.new
        @posts = Post.order("created_at DESC")

        @trainers = Trainer.all

        @answer = Answer.new
        @answers = Answer.all

        @places = Place.all
        @categories = Category.all
        # @categoly = Category.new
        @relationship =Relationship.new
        
    end




    def search
          @posts = Post.where('title LIKE(?)', "%#{params[:search]}%").limit(20)
    end

     def trainer_search
          @trainers = Place.find_by('city LIKE(?)', "%#{params[:t_search]}%").trainers.limit(20)
    end



end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  def show
    @trainer = Trainer.find(params[:id])
    @post = Post.new
    @posts = Post.where(trainer_id: params[:id]).order("created_at DESC")
  end

  def edit
  end

  def update
     current_trainer.update(update_params)
  end



  private
    def update_params
      params.require(:trainer).permit(:name, :profile, :avatar, :place_id, :category_id)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show

    @user = User.find(params[:id])
     @post = Post.new
     @posts = Post.where(user_id: params[:id]).order("created_at DESC")

  end

  def edit
  end

  def update
     current_user.update(update_params)
  end


  private
    def update_params
      params.require(:user).permit(:name, :profile, :avatar, :place_id, :category_id)
    end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/identifications_helper.rb
module IdentificationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/top/_post.html.erb
  <li class="main_content  img-rounded">
      <%if post.user_id%>
<%=link_to (user_path(post.user.id)) do%>
            <div class="main_c_left">
            <%= image_tag("#{post.user.avatar}", size: "50x50", class: 'img-circle' , style: 'margin-right:10px;', alt: "profile") %>
            </div>

           <div class="main_c_right"><time class="t_line_time"><%=time_ago_in_words post.updated_at%></time>
                <h5 class="t_line_name">
                <%=post.user.name%>
                </h5>
                <h4 class="t_title"><%=post.title%></h4>
                <%if post.avatar.present?%>
                <%= image_tag("#{post.avatar}", class: 't_photo' , alt: "img") %>
                <%else%>
                <%end%>
                <p><%=post.post%></p>
          </div>
    <%end%>
<%elsif post.trainer_id%>
    <%= link_to (trainer_path(post.trainer.id)) do%>

            <div class="main_c_left">
            <%= image_tag("#{post.trainer.avatar}", size: "50x50", class: 'img-circle' , style: 'margin-right:10px;', alt: "profile") %>
            </div>

           <div class="main_c_right"><time class="t_line_time"><%=time_ago_in_words post.updated_at%></time>
                <h5 class="t_line_name">
                <%=post.trainer.name%>
                </h5>
                <h4 class="t_title"><%=post.title%></h4>
                <%if post.avatar.present?%>
                <%= image_tag("#{post.avatar}", class: 't_photo' , alt: "img") %>
                <%else%>
                <%end%>
                <p><%=post.post%></p>
          </div>
     <%end%>


<%end%>

      <div class="answer_buttons">
<%if user_signed_in? %>
    <%if post.trainer_id %>
    <%=link_to 'フォロー', "/relationships/#{post.trainer.id}/?type=#{post.trainer.class}", method: :post %>
    <%elsif post.user_id %>
    <%unless post.user_id == current_user.id %>
    <%=link_to 'フォロー', "/relationships/#{post.user.id}/?type=#{post.user.class}", method: :post %>
    <%end%>
    <%end%>
<%elsif trainer_signed_in? %>
    <%if post.trainer_id %>
    <%unless post.trainer_id == current_trainer.id %>
    <%=link_to 'フォロー', "/relationships/#{post.trainer.id}/?type=#{post.trainer.class}", method: :post %>
    <%end%>
    <%elsif post.user_id %>
    <%=link_to 'フォロー', "/relationships/#{post.user.id}/?type=#{post.user.class}", method: :post %>
    <%end%>

<%end%>


 <%= form_tag(new_answer_path, method: :get, class: "") do %>
      <%= hidden_field_tag(:post_id, post.id) %>
      <%= submit_tag("回答する") %>
    <% end %>


  <%if post.answers.count >= 1 %>
      <%- post.answers.each do |answer|%>
            <ul>
              <li class="coment_content">
                <%if answer.trainer_id%>
                    <%= image_tag("#{answer.trainer.avatar}", class: 'c_photo' , alt: "img") %>
                    <%=answer.trainer.name%><br>
                    <%= answer.answer%>
                <%elsif answer.user_id%>
                    <%= image_tag("#{answer.user.avatar}", class: 'c_photo' , alt: "img") %>
                    <%=answer.user.name%><br>
                    <%= answer.answer%>
                <%end%>

              </li>
            </ul>
      <%end%>
    <%else%>
<%end%>


</div>

    </li>

app/views/top/index.html.erb
      <div class="maincullumn col-md-8 col-xs-12" >

          <div class="main_content_top img-rounded clearfix">


<% if user_signed_in? %>

              <h2 class="h3" style="margin-bottom:20px">
              <%=image_tag("#{current_user.avatar}", size: "50x50", class: 'img-circle' , style: 'margin-right:10px;', alt: "profile") %>
              あなたの投稿</h2>


<%elsif trainer_signed_in? %>

<h2 class="h3" style="margin-bottom:20px">
              <%=image_tag("#{current_trainer.avatar}", size: "50x50", class: 'img-circle' , style: 'margin-right:10px;', alt: "profile") %>
              あなたの投稿</h2>
<%end%>

   <time class="t_post_time"><%=Date.today %></time>

<% if user_signed_in? %>
      <% unless current_user.full_profile?  %>
       <%= link_to "まずはプロフィールを完成させましょう！", edit_user_path(current_user) %>
      <% else %>
                  <%= form_for(@post, html: {style: 'clear:both;'} ,) do |f| %>
                        <div class="form-group file" id="i_avatar">
                        <%= f.file_field :avatar, class: "floating-label", placeholder: "画像アップロード" %>
                        </div>
                            <div id="p_title">
                            <%= f.text_field :title, placeholder: "タイトル"  %>
                            </div>
                        <div id="p_textarea">
                        <%= f.text_area :post, placeholder: "今日はどんなトレーニングをしましたか？", maxlength: "200" %>
                        </div>
                      <%= f.submit "投稿する" %>
                  <% end %>
       <% end %>

<%elsif trainer_signed_in? %>
      <% unless current_trainer.full_profile?  %>
             <%= link_to "まずはプロフィールを完成させましょう！", edit_trainer_path(current_trainer) %>
             <% else %>
                        <%= form_for(@post, html: {style: 'clear:both;'} ,) do |f| %>
                              <div class="form-group file" id="i_avatar">
                              <%= f.file_field :avatar, class: "floating-label", placeholder: "画像アップロード" %>
                              </div>
                                  <div id="p_title">
                                  <%= f.text_field :title, placeholder: "タイトル"  %>
                                  </div>
                              <div id="p_textarea">
                              <%= f.text_area :post, placeholder: "今日はどんなトレーニングをしましたか？", maxlength: "200" %>
                              </div>
                            <%= f.submit "投稿する" %>
                        <% end %>
      <% end %>
  <% end %>
 </div>

<ul>
  <%=render partial: "top/post", collection: @posts %>
</ul>
 </div><!-- maincullumn-end -->



<div class="sidecullumn col-md-4 col-xs-12" >
        <div class="profile_content img-rounded">

            <% if user_signed_in? %>
                  <% unless current_user.full_profile?  %>
                      <h3 class="profile_name text-center"><%=current_user.name %></h3>
                  <%else%>
                      <div class="profile_mar">
                      <%= image_tag("#{current_user.avatar}", size: "130x130", class: 'img-circle' , alt: "profile") %>
                      </div>
                      <h3 class="profile_name text-center"><%=current_user.name %></h3>
                      <%= current_user.place.city %><br>
                      <%= current_user.category.category %>
                      <p class="side_text"><%=current_user.profile %></p>
                  <%end%>

            <%elsif trainer_signed_in? %>
                  <% unless current_trainer.full_profile?  %>
                    <h3 class="profile_name text-center"><%=current_trainer.name %></h3>
                  <%else%>
                    <div class="profile_mar">
                    <%= image_tag("#{current_trainer.avatar}", size: "130x130", class: 'img-circle' , alt: "profile") %>
                    </div>
                    <h3 class="profile_name text-center"><%=current_trainer.name %></h3>
                     <%= current_trainer.place.city %><br>
                      <%= current_trainer.category.category %>
                    <p class="side_text"><%=current_trainer.profile %></p>
                  <%end%>
            <%end%>

        </div><!--profile_content-->


        <div class="side_content img-rounded">
             <div class="search pull-right">

             <%= form_tag('/top/trainer_search', method: :get) do %>
                        <form action="/" name="search2" method="post">
                              <dl class="search2">
                                <dt><input type="text" name="t_search" value="" placeholder="トレーナー検索" /></dt>
                                <dd><button><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button></dd>
                              </dl>
                            </form>

              <% end %>


                        </div>
        </div>
    </div>

app/views/top/search.html.erb
      <div class="maincullumn col-md-8 col-xs-12" >

          <div class="main_content_top img-rounded clearfix">



<ul class="">

      <% @posts.each do |post| %>
      <li>
       <p><%=post.title%></p>
       <p><%=post.post%></p>
      </li>
      <% end %>
</ul>














          </div>
 </div><!-- maincullumn-end -->



<div class="sidecullumn col-md-4 col-xs-12" >
        <div class="profile_content img-rounded">

        </div><!--profile_content-->


        <div class="side_content img-rounded">
        </div>
 </div>

app/views/top/trainer_search.html.erb
      <div class="maincullumn col-md-8 col-xs-12" >

          <div class="main_content_top img-rounded clearfix">



<ul class="">

      <% @trainers.each do |trainer| %>
      <li>
       <p><%=trainer.name%></p>
      </li>
      <% end %>
</ul>














          </div>
 </div><!-- maincullumn-end -->



<div class="sidecullumn col-md-4 col-xs-12" >
        <div class="profile_content img-rounded">

        </div><!--profile_content-->


        <div class="side_content img-rounded">
        </div>
 </div>