config/routes.rb
Rails.application.routes.draw do

  devise_for :trainers, controllers: {
  sessions:      'trainers/sessions',
  passwords:     'trainers/passwords',
  registrations: 'trainers/registrations'
  }
  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
  }

resources :identifications, only: :index
resources :top, only: :index do
  collection do
  get 'search'
  get 'trainer_search'
end

end
resources :users, only: [:show, :edit, :update]
resources :trainers, only: [:show, :edit, :update]
resources :posts, only: :create
resources :answers, only: [:new,:create]
 post  'relationships/:id'      =>  'relationships#create'
 # :idでモデルの持つid情報を取得

root 'top#index'
end

app/models/trainer.rb
class Trainer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :posts
         has_many :answers
         belongs_to :place
         belongs_to :category
         has_many :relationships, dependent: :destroy
         has_many :relationships, as: :follower, dependent: :destroy


  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>"}
  validates_attachment_content_type :avatar, content_type: ["image/jpg","image/jpeg","image/png"]

def full_profile?
    avatar? && profile?
  end

end

app/controllers/trainers/confirmations_controller.rb
class Trainers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/trainers/omniauth_callbacks_controller.rb
class Trainers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/trainers/passwords_controller.rb
class Trainers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/trainers/registrations_controller.rb
class Trainers::RegistrationsController < Devise::RegistrationsController
    skip_before_action :identification_page
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/trainers/sessions_controller.rb
class Trainers::SessionsController < Devise::SessionsController
    skip_before_action :identification_page
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/trainers/unlocks_controller.rb
class Trainers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  def show
    @trainer = Trainer.find(params[:id])
    @post = Post.new
    @posts = Post.where(trainer_id: params[:id]).order("created_at DESC")
  end

  def edit
  end

  def update
     current_trainer.update(update_params)
  end



  private
    def update_params
      params.require(:trainer).permit(:name, :profile, :avatar, :place_id, :category_id)
    end

end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/views/trainers/edit.html.erb
<div class="col-md-2 col-xs-0"></div>
      <div class="maincullumn col-md-8 col-xs-12" >

          <div class="main_content_top img-rounded clearfix">

  <h2 class="h3" style="margin-bottom:20px"><%= image_tag("profile.jpg", size: "50x50", class: 'img-circle' , style: 'margin-right:10px;', alt: "profile") %>編集画面</h2>

<%= form_for current_trainer,html: {style: 'clear:both;'}  do |f| %>

<div class="form-group file" id="i_avatar">
        <%= f.file_field :avatar, class: "form-control floating-label", placeholder: "画像アップロード" %>
      </div>

        <div class="form-group">
            <div class="field" id="i_name" >
                <div class="label"><%= f.label :name %><br />
                <%= f.text_field :name , placeholder: 'name'%>
                </div>
            </div>
        </div>

<div class="form-group">

 <%= f.collection_select :place_id, Place.all, :id,:city %>

 </div>

 <div class="form-group">

 <%= f.collection_select :category_id, Category.all, :id,:category %>

 </div>

         <div id="p_textarea">
      <%= f.text_area :profile, placeholder: "あなたのプロフィールを記入してください", maxlength: "200" %>
      </div>


     <div class="actions">
        <%= f.submit "送信", class: "" %>
      </div>
    <% end %>




  </div>
 </div><!-- maincullumn-end -->



 <div class="col-md-2 col-xs-0"></div>

app/views/trainers/show.html.erb
      <div class="maincullumn col-md-8 col-xs-12" >

<%if trainer_signed_in?%>

<div class="main_content_top img-rounded clearfix">
    <%if @trainer.id == current_trainer.id%>
                  <h2 class="h3" style="margin-bottom:20px">
                  <%=image_tag("#{@trainer.avatar}", size: "50x50", class: 'img-circle' , style: 'margin-right:10px;', alt: "profile") %>
                  あなたの投稿</h2>


                  <time class="t_post_time"><%=Date.today %></time>

        <%= form_for(@post, html: {style: 'clear:both;'} ,) do |f| %>
            <div id="p_title">
            <%= f.text_field :title, placeholder: "タイトル"  %>
            </div>
            <div id="p_textarea">
            <%= f.text_area :post, placeholder: "今日はどんなトレーニングをしましたか？", maxlength: "200" %>
            </div>
            <%= f.submit "投稿する" %>
        <% end %>
    <%elsif%>
    <p><%= @trainer.name%>さんの投稿一覧</p>
    <%end%>
</div>
<%elsif user_signed_in?%>


<div class="main_content_top img-rounded clearfix">
    <p><%= @trainer.name%>さんの投稿一覧</p>
</div>

<%end%>

<ul style="margin-top:25px">
  <%=render partial: "top/post", collection: @posts %>
</ul>
 </div><!-- maincullumn-end -->










    <div class="sidecullumn col-md-4 col-xs-12" >

<div class="profile_content img-rounded">


      <div class="profile_mar">
      <%= image_tag("#{@trainer.avatar}", size: "130x130", class: 'img-circle' , alt: "profile") %>
      </div>
          <h3 class="profile_name text-center"><%=@trainer.name %></h3>
                <%= @trainer.place.city %><br>
                      <%= @trainer.category.category %>
             <p class="side_text"><%=@trainer.profile%></p>
             <%if trainer_signed_in?%>
             <%if @trainer.id == current_trainer.id%>
             <%= link_to "プロフィール編集", edit_trainer_path(current_trainer) %>
            <%end%>
            <%end%>

 </div>


        <div class="side_content img-rounded">
        <p>これはサイドカラムです。これはダミープロフィールです。ご注意ください。これはダミープロフィールです。ご注意ください。これはダミープロフィールです。ご注意ください。これはサイドカラムです。これはダミープロフィールです。ご注意ください。これはダミープロフィールです。ご注意ください。これはダミープロフィールです。ご注意ください。これはサイドカラムです。これはダミープロフィールです。ご注意ください。これはダミープロフィールです。ご注意ください。これはダミープロフィールです。ご注意ください。これはサイドカラムです。これはダミープロフィールです。ご注意ください。これはダミープロフィールです。ご注意ください。これはダミープロフィールです。ご注意ください。これはサイドカラムです。これはダミープロフィールです。ご注意ください。これはダミープロフィールです。ご注意ください。これはダミープロフィールです。</p>
        </div>
    </div>

app/views/trainers/update.html.erb
<div class="col-md-2 col-xs-0"></div>
      <div class="maincullumn col-md-8 col-xs-12" >

          <div class="main_content_top img-rounded clearfix">

  <h3>プロフィールの編集が完了しました。</h3>
    <%= link_to "ホームに戻る", root_path %>

  </div>
 </div><!-- maincullumn-end -->



 <div class="col-md-2 col-xs-0"></div>